### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by axsddlr** [dumax315/download-tiktok#1]
```
'NoneType' object is not subscriptable
cannot unpack non-iterable NoneType object
```

**Comment by dumax315** [comment]
I just made a new commit, you will get more consistent results running in repl.it. Also, sometimes the web scraping just fails, ¯\_(ツ)_/¯

**Comment by dumax315** [comment]
Since I have added new files for self hosting I'm going to mark this as resolved.
